Am adaugat cheat sheet cu noua materie
Vlaaaaaaad/FMI-public-materials pull request #3
Opened 2017-06-23 17:16 UTC by ericpts

2017-06-23 20:10 UTC, Vlaaaaaaad requested changes
Some relevant info is deleted, changes are required to merge this.

2017-06-23 20:10 UTC, Vlaaaaaaad commented on MetodeDeDezvoltareSoftware/MDS.md
> -[TOC]
This is needed for Table of Contents if using Stackedit.

2017-06-23 20:10 UTC, Vlaaaaaaad commented on MetodeDeDezvoltareSoftware/MDS.md
> -#Z
Do not delete info for Z, it might be needed in the future.

2017-06-23 20:10 UTC, Vlaaaaaaad commented on MetodeDeDezvoltareSoftware/MDS.md
> +```java
Keep the `java` to mark the language. This is useful for syntax highlighting when exporting.

2017-06-23 20:10 UTC, Vlaaaaaaad commented on MetodeDeDezvoltareSoftware/MDS.md
> -```
Why did you delete this?

2017-06-23 20:10 UTC, Vlaaaaaaad commented on MetodeDeDezvoltareSoftware/MDS.md
> -![Cele 14 tipuri de diagrame UML 2.0](https://upload.wikimedia.org/wikipedia/commons/e/ed/UML_diagrams_overview.svg)
Keep this.

2017-06-23 20:10 UTC, Vlaaaaaaad commented on MetodeDeDezvoltareSoftware/MDS.md
> -import org.junit.*;
+1 for deleting imports

2017-06-23 20:10 UTC, Vlaaaaaaad commented on MetodeDeDezvoltareSoftware/MDS.md
> -#Licente
Keep this info.

2017-06-24 05:39 UTC, ericpts commented
Undid all changes in MDS.md, so all the new content is now in MDSv2.*

2017-06-24 08:14 UTC, Vlaaaaaaad approved these changes

2017-06-24 08:14 UTC, Vlaaaaaaad commented
Not ideal, but a good compromise.

Thank you very much for contributing!

2017-06-24 08:15 UTC, merged